# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  body1_joint:
    has_velocity_limits: true
<<<<<<< HEAD
    max_velocity: 3.1415
=======
    max_velocity: 100
>>>>>>> 50b6ede30c53f4e4f2c6fcce5bac338932e941fc
    has_acceleration_limits: false
    max_acceleration: 0
  body2_joint:
    has_velocity_limits: true
<<<<<<< HEAD
    max_velocity: 3.1415
=======
    max_velocity: 100
>>>>>>> 50b6ede30c53f4e4f2c6fcce5bac338932e941fc
    has_acceleration_limits: false
    max_acceleration: 0
  body3_joint:
    has_velocity_limits: true
<<<<<<< HEAD
    max_velocity: 3.1415
=======
    max_velocity: 100
>>>>>>> 50b6ede30c53f4e4f2c6fcce5bac338932e941fc
    has_acceleration_limits: false
    max_acceleration: 0
  body4_joint:
    has_velocity_limits: true
<<<<<<< HEAD
    max_velocity: 3.1415
=======
    max_velocity: 100
>>>>>>> 50b6ede30c53f4e4f2c6fcce5bac338932e941fc
    has_acceleration_limits: false
    max_acceleration: 0
  body5_joint:
    has_velocity_limits: true
<<<<<<< HEAD
    max_velocity: 3.1415
=======
    max_velocity: 100
>>>>>>> 50b6ede30c53f4e4f2c6fcce5bac338932e941fc
    has_acceleration_limits: false
    max_acceleration: 0
  body6_joint:
    has_velocity_limits: true
<<<<<<< HEAD
    max_velocity: 3.1415
=======
    max_velocity: 100
>>>>>>> 50b6ede30c53f4e4f2c6fcce5bac338932e941fc
    has_acceleration_limits: false
    max_acceleration: 0